### ISSUE TITLE
Issue with Read More Button Position

### ISSUE THREAD

**Issue by seoeunHong** [ossd-s23/rufaida99-k-weekly#1]
I noticed that your each Read More buttons are located out side of the each post's separation line. I looked over your code and found you have an order issue [on this code](https://github.com/ossd-s23/rufaida99-k-weekly/blob/8e1a5a1e08c2d98540815107fda8d475146630ce/index.html#L17-L19)

**Comment by nicoleSosa** [comment]
@rufaida99-k I would like to claim this issue.

**Comment by rufaida99-k** [comment]
Go ahead! :) @nicoleSosa

**Comment by nicoleSosa** [comment]
Will do! Thank you.

**Comment by rufaida99-k** [comment]
@nicoleSosa merged, thanks! :)
